@startuml Pipeline Flowchart
|audio_mnist|
package "audio-mnist" {
    :start|
    partition "audiomnist.sh" {
        :set paths;
        :run script;
        partition "audiomnist.py" {
            :data preparation;
            :feature engineering;
            :data splitting;
            :model tuning;
            :model training;
            :model prediction;
            :data to postgres;
        }
        :write to log;
    }
    :end|
}
@enduml
