learning_rate: [0.01, 0.05, 0.1]  # Learning rate
max_depth: [5, 7, 9]              # Maximum depth of a tree
n_estimators: [100, 200, 300]     # Number of iterations (trees)
objective: [binary:logistic]      # Loss function
tree_method: [hist]               # Histogram tree grow method
