learning_rate: 0.1          # Learning rate eta
max_depth: 9                # Maximum depth of a tree
n_estimators: 300           # Number of iterations (trees)
objective: binary:logistic  # Loss function
tree_method: hist           # Tree grow method
