learning_rate: [0.01, 0.05, 0.1]  # Learning Rate
max_depth: [5, 7, 9]              # Max Depth Of Tree
n_estimators: [100, 200, 300]     # Number Of Estimators
objective: [binary:logistic]      # Objective Function
tree_method: [hist]               # Tree Method
