project: "C:/GitProjects/audio-mnist"
meta: "audioMNIST_meta.txt"
data:
  prepared: "data_prepared.csv"
  engineered: "data_engineered.csv"
  predicted: "data_predicted.csv"
image:
  exit: "exit.png"
  info: "info.png"
  logo: "logo.png"
  run: "run.png"
param:
  model_param: "model_parameters.yaml"
  model_hyperparam: "model_hyperparameters.yaml"
plot:
  audio: "audio/audio_{0}_{1}_{2}.png"
  stft: "stft/stft_{0}_{1}_{2}.png"
  col_dist: "column_distribution.png"
  col_box: "column_box.png"
  conf_matrix: "confusion_matrix.png"
  corr_matrix: "correlation_matrix.png"
  feat_imp: "feature_importance.png"
  model_acc: "model_accuracy.png"
  model_loss: "model_loss.png"
  shap_sum: "shapley_summary.png"
result:
  model_obj: "model_object.pkl"
  model_param_best: "model_param_best.yaml"
  model_res: "model_result.yaml"
text:
  about: "about.txt"
  cols: "columns.txt"
split:
  val: 0.10
  test: 0.10
threshold:
  corr: 0.95
target: "gender"
labels: ["Female", "Male"]
predicted: predicted
