project_path: "C:/GitProjects/AudioMNIST"
meta_data: "audioMNIST_meta.txt"
data:
  prepared: "data_prepared.csv"
  engineered: "data_engineered.csv"
  predicted: "data_predicted.csv"
parameters:
  model_parameters: "model_parameters.yaml"
  model_hyperparameters: "model_hyperparameters.yaml"
plots:
  column_distribution: "column_distribution.png"
  confusion_matrix: "confusion_matrix.png"
  correlation_matrix: "correlation_matrix.png"
  feature_importance: "feature_importance.png"
  model_accuracy: "model_accuracy.png"
  model_loss: "model_loss.png"
  shapley_summary: "shapley_summary.png"
results:
  model_best_param: "model_best_param.yaml"
  model_results: "model_results.yaml"
  model_object: "model_object.pkl"
thresholds:
  correlation: 0.95
targets: ["gender", "digit"]
labels: ["Female", "Male"]
predicted: predicted
