project_path: "C:/GitProjects/AudioMNIST"
meta_data: "audioMNIST_meta.txt"
parameters:
  model_static: "model_parameters.yaml"
  model_dynamic: "model_hyperparameters.yaml"
data:
  data_prepared: "data_prepared.csv"
  data_engineered: "data_engineered.csv"
  data_final: "data_final.csv"
plots:
  column_distribution: "column_distribution.png"
  correlation_matrix: "correlation_matrix.png"
  feature_importance: "feature_importance.png"
  confusion_matrix: "confusion_matrix.png"
  model_loss: "model_loss.png"
  model_accuracy: "model_accuracy.png"
results:
  model_param_best: "model_param_best.yaml"
  model_results: "model_results.yaml"
  model_object: "model_object.pkl"
threshold: 0.95
targets: ["gender", "digit"]
labels: ["Female", "Male"]
predicted: predicted
